---
- name: config | Configuring Wordpress
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ wordpress_apache2_web_root }}/wordpress/wp-config.php"
    mode: "0640"
  become: true

- name: config | Configuring Wordpress Permissions
  ansible.builtin.file:
    path: "{{ wordpress_apache2_web_root }}"
    state: directory
    owner: "{{ wordpress_apache2_web_owner }}"
    group: "{{ wordpress_apache2_web_group }}"
    recurse: true
  become: true
