---
# tasks file for ansible-wordpress

- name: Include set_facts tasks
  ansible.builtin.include_tasks:
    file: set_facts.yml

- name: Include db tasks
  ansible.builtin.include_tasks:
    file: db.yml

- name: Include install tasks
  ansible.builtin.include_tasks:
    file: install.yml

- name: Include config tasks
  ansible.builtin.include_tasks:
    file: config.yml
